# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_P = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_P.setGeometry(QtCore.QRect(160, 90, 521, 91))
        self.txt_P.setObjectName("txt_P")
        self.txt_K = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_K.setGeometry(QtCore.QRect(160, 210, 521, 31))
        self.txt_K.setObjectName("txt_K")
        self.txt_C = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_C.setGeometry(QtCore.QRect(160, 260, 521, 101))
        self.txt_C.setObjectName("txt_C")
        self.lbl_C = QtWidgets.QLabel(self.centralwidget)
        self.lbl_C.setGeometry(QtCore.QRect(300, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.lbl_C.setFont(font)
        self.lbl_C.setObjectName("lbl_C")
        self.lbl_P = QtWidgets.QLabel(self.centralwidget)
        self.lbl_P.setGeometry(QtCore.QRect(56, 90, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_P.setFont(font)
        self.lbl_P.setObjectName("lbl_P")
        self.lbl_K = QtWidgets.QLabel(self.centralwidget)
        self.lbl_K.setGeometry(QtCore.QRect(60, 210, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_K.setFont(font)
        self.lbl_K.setObjectName("lbl_K")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 260, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_E = QtWidgets.QPushButton(self.centralwidget)
        self.btn_E.setGeometry(QtCore.QRect(200, 410, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_E.setFont(font)
        self.btn_E.setObjectName("btn_E")
        self.btn_D = QtWidgets.QPushButton(self.centralwidget)
        self.btn_D.setGeometry(QtCore.QRect(550, 410, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_D.setFont(font)
        self.btn_D.setObjectName("btn_D")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_C.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.lbl_P.setText(_translate("MainWindow", "Plain text:"))
        self.lbl_K.setText(_translate("MainWindow", "Key:"))
        self.label_4.setText(_translate("MainWindow", "CipherText:"))
        self.btn_E.setText(_translate("MainWindow", "Encrypt"))
        self.btn_D.setText(_translate("MainWindow", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
