# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 510)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(470, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lbl_P = QtWidgets.QLabel(self.centralwidget)
        self.lbl_P.setGeometry(QtCore.QRect(0, 130, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_P.setFont(font)
        self.lbl_P.setObjectName("lbl_P")
        self.lbl_C = QtWidgets.QLabel(self.centralwidget)
        self.lbl_C.setGeometry(QtCore.QRect(0, 260, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_C.setFont(font)
        self.lbl_C.setObjectName("lbl_C")
        self.lbl_Sig = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Sig.setGeometry(QtCore.QRect(620, 260, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_Sig.setFont(font)
        self.lbl_Sig.setObjectName("lbl_Sig")
        self.lbl_In = QtWidgets.QLabel(self.centralwidget)
        self.lbl_In.setGeometry(QtCore.QRect(610, 130, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_In.setFont(font)
        self.lbl_In.setObjectName("lbl_In")
        self.txt_P = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_P.setGeometry(QtCore.QRect(80, 130, 481, 87))
        self.txt_P.setObjectName("txt_P")
        self.txt_C = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_C.setGeometry(QtCore.QRect(90, 260, 481, 87))
        self.txt_C.setObjectName("txt_C")
        self.txt_In = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_In.setGeometry(QtCore.QRect(710, 130, 481, 87))
        self.txt_In.setObjectName("txt_In")
        self.txt_Signature = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txt_Signature.setGeometry(QtCore.QRect(710, 260, 481, 87))
        self.txt_Signature.setObjectName("txt_Signature")
        self.btn_En = QtWidgets.QPushButton(self.centralwidget)
        self.btn_En.setGeometry(QtCore.QRect(160, 370, 93, 28))
        self.btn_En.setObjectName("btn_En")
        self.btn_Gen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Gen.setGeometry(QtCore.QRect(680, 50, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_Gen.setFont(font)
        self.btn_Gen.setObjectName("btn_Gen")
        self.btn_De = QtWidgets.QPushButton(self.centralwidget)
        self.btn_De.setGeometry(QtCore.QRect(400, 370, 93, 28))
        self.btn_De.setObjectName("btn_De")
        self.btn_Sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Sign.setGeometry(QtCore.QRect(800, 370, 93, 28))
        self.btn_Sign.setObjectName("btn_Sign")
        self.btn_Verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Verify.setGeometry(QtCore.QRect(1020, 370, 93, 28))
        self.btn_Verify.setObjectName("btn_Verify")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1215, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.lbl_P.setText(_translate("MainWindow", "Plain text:"))
        self.lbl_C.setText(_translate("MainWindow", "Ciphertext:"))
        self.lbl_Sig.setText(_translate("MainWindow", "Signature:"))
        self.lbl_In.setText(_translate("MainWindow", "Information:"))
        self.btn_En.setText(_translate("MainWindow", "Encrypt"))
        self.btn_Gen.setText(_translate("MainWindow", "Generate Keys"))
        self.btn_De.setText(_translate("MainWindow", "Decrypt"))
        self.btn_Sign.setText(_translate("MainWindow", "Sign"))
        self.btn_Verify.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
